#!/bin/bash

curl -sL -O https://github.com/neonichu/ruby-domain_name/releases/download/v0.5.99999999/domain_name-0.5.99999999.gem
sudo gem install domain_name-0.5.99999999.gem
sudo gem install --conservative xcode-install
rm -f domain_name-0.5.99999999.gem

sudo gem install cocoapods xcpretty xcodegen

echo -e "\nNow choose a version and install using xcversion install VERSION"
echo -e "Then choose it by running xcversion select VERSION --symlink"
